language: haskell

sudo: false
cache:
  directories:
  - $HOME/.stack/
  - $HOME/racket/

before_install:
- mkdir -p ~/.local/bin
- export PATH=~/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- chmod a+x ~/.local/bin/stack
- cat /proc/cpuinfo | grep name
- stack setup

install:
  - pwd
  - cd accelerack && ./.prevalidate.sh && cd ..

script:
  - pwd
  - cd accelerack && ./.mainvalidate.sh && cd ..
