// Include Haskell FFI file, which we will use to initialize a Haskell runtime
#include "HsFFI.h"

// Generated by GHC when it compiles the "foreign export":
#include "Example_stub.h"

int main( int argc, char *argv[] )
{
  // Initialize Haskell Runtime _before_ any calls to the Haskell code
  hs_init (&argc, &argv);

  // Make a call to Haskell code
  entrypoint(33);

  hs_exit();
}

int wrap(void)
{
  int argc = 2;
  char *argv[] = { "+RTS", "-A32m", 0 };
  char **pargv = argv;

  // Initialize Haskell runtime
  hs_init(&argc, &pargv);

  // Make a call to Haskell code
  entrypoint(33);

  hs_exit();
}
